name: Unit Testing
on: [push]
jobs:
  unit-testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        operating-systems: ['ubuntu-latest']
    services:
      db:
        image: postgres:13.4
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testing_db
        ports:
          - 5432:5432
        options: --health-cmd=pg_isready --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Github Checkout
        uses: actions/checkout@v2
      
      - name: Install Node v14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
    
      - name: See the list
        run: ls -l
        
      - name: Install npm dependencies
        run: npm install
      
      - name: Run unit testing
        run: npm run test
